### ISSUE TITLE
Invitations are not working

### ISSUE THREAD

**Issue by marcgc21** [uramakilab/remote-usability-lab#25]
It seems that it does not work the invitations anymore, can someone take a look?

**Comment by afrikiudl** [comment]
Even all people that was registrered on the tool, They didn't recive any email.

**Comment by afrikiudl** [comment]
Hello, 
and I have to configure the invitations again? Or the message have seen sended when the bug was fixed? 
Thanks!

**Comment by KarinePistili** [comment]
Hi, unfortunately you will have to send the invitations again :(

**Comment by afrikiudl** [comment]
It is possible consider on the future a new funcionality related with this task "resend invitation"?
Now, there are "cancel invitation", but I think that the funcionality "resend invitation" it could be necessary...
In some ocasions, the user don't accept the invitation and you have to resend again.

**Comment by marcgc21** [comment]
@afrikiudl will adrress your comment and solved as fast as possible. I beliave that is a feature quite interesting!

**Comment by afrikiudl** [comment]
Hi,
I have 2 problems with retlab.
1) I can add a colaborator with this email (albagarcia149.com@gmail.com), but the email that he receive, don't link to retlab otherwise other web (I don't remembre where...)

Other user, that have administrator role, can't save the results of her heuristics.

Do you know what is happen? 
Can you help me in these problems?

if you need more information, please contact me 
Thanks
A

**Comment by afrikiudl** [comment]
Hi,
I have 2 problems with retlab.

1)I can add a colaborator with this email ([albagarcia149.com@gmail.com](mailto:albagarcia149.com@gmail.com)), but the email that he receive, don't link to retlab otherwise other web (I don't remembre where...)
2) Other user, that have administrator role, can't save the results of her heuristics.

Do you know what is happen?
Can you help me in these problems?

if you need more information, please contact me
Thanks
A

**Comment by KarinePistili** [comment]
Hello, 

For the first problem, can you send us what is the URL that the email redirects the user to? We've done some tests and could not reproduce the error

In the case of the second error, when you say save the results of the heuristics, you mean by updating the test questions or by answering the test? If the administrator is trying to answer it by using the preview tab, it is not going to work properly as it is only for previewing 

We'll keep on trying to reproduce the errors, if we find anything new I'll let you know :)

**Comment by afrikiudl** [comment]
Hello,
About the first problem, I think that all users could solve. If I view other problems about this, I'll send you.

About the second error, I have a doubt. ¿Admins can't do the test? Is not possible?
And ¿Only can evaluators role?
I didn't kwow about this, and I thought that evaluators also could do the test.
And If one admin wants make the test, What will have to do? 
To have one email to evaluator role and other to admin role?

**Comment by KarinePistili** [comment]
Hi, yes right now only evaluators could answer the test. At the moment you would have to either use another email or to change the user admin role to evaluator on the collaborators tab of the test.

**Comment by afrikiudl** [comment]
Oks. Thanks.
But this is a restriccion of the tool?

**Comment by KarinePistili** [comment]
Yes, at the moment the admins can't answer as it is a feature that is not implemented. But if you think that the admins should be able to answer it as well, we can add an issue to implement this functionality soon.

**Comment by afrikiudl** [comment]
I thing that could be good. But now is not possible, because We are using the tool. But the proposal that you said me, about include 2 emails for the same person, has been a possible solution. Thanks!

**Comment by KarinePistili** [comment]
You're welcome!
